services:
  sahayak-db:
    image: postgres:14
    container_name: sahayak-db
    restart: always
    environment:
      POSTGRES_DB: sahayak_gw_db
      POSTGRES_USER: sahayak_gw_user
      POSTGRES_PASSWORD: sahayak_gw_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sahayak_gw_user -d sahayak_gw_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  sahayak-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sahayak-gateway
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      sahayak-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
