"""initial migration

Revision ID: 473f4efda169
Revises: 
Create Date: 2025-07-26 13:57:04.467327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473f4efda169'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('mpin_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_index(op.f('ix_users_index'), 'users', ['index'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_index'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
